meta_product_name: "Floatify"
meta_title: "Floatify - rent a boat for your adventure"
meta_description: "Rent a boat directly from a boat owner and start your adventure at sea."
meta_image: "meta-img.png" # should exist in `app/assets/images/`